version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"  # Exponer el puerto de la aplicación
    depends_on:
      - database  # Asegurar que la base de datos esté lista antes de iniciar
    volumes:
      - ./app:/app  # Montar el código de la aplicación (opcional)
    networks:
      - app_network

  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"  # Exponer el puerto PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Persistir los datos
    networks:
      - app_network

volumes:
  postgres_data:  # Volumen para datos de la base de datos

networks:
  app_network:  # Red compartida para app y base de datos
